name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:

  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: VirtusLab/scala-cli-setup@main
    - uses: taiki-e/install-action@just
    - name: Install Playwright
      run: just setupPlaywright
    - name: compile
      run: just compile
    - name: test
      run: just test


  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: VirtusLab/scala-cli-setup@main

    - name: Publish
      run: scala-cli publish . --power --user env:PUBLISH_USER --password env:PUBLISH_PASSWORD --gpg-key env:PUBLISH_SECRET_KEY --gpg-option --pinentry-mode --gpg-option loopback --gpg-option --passphrase --gpg-option env:PUBLISH_SECRET_KEY_PASSWORD --suppress-experimental-feature-warning
      env:
        PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
        PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        PUBLISH_SECRET_KEY: ${{ secrets.PUBLISH_SECRET_KEY }}
        PUBLISH_SECRET_KEY_PASSWORD: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
