name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:

  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: VirtusLab/scala-cli-setup@main
    - uses: taiki-e/install-action@just
    - name: Install Playwright
      run: just setupPlaywright
    - name: compile
      run: just compile
    - name: test
      run: just test


  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: VirtusLab/scala-cli-setup@main

    - name: Publish
      run: scala-cli publish . --power --secret-key value:${{secrets.PUBLISH_SECRET_KEY}} --secret-key-password value:${{secrets.PUBLISH_SECRET_KEY_PASSWORD}} --user value:${{ secrets.PUBLISH_USER }} --password value:${{secrets.PUBLISH_PASSWORD}}